[v1]
"qubit-infra-dependency 0.1.0 (git+https://github.com/qubit-ltd/rs-infra-dependency.git?rev=28da1a40c2a33ff745900abdff31c848c4a9ba91#28da1a40c2a33ff745900abdff31c848c4a9ba91)" = ["rs-infra-dependency"]
