[rs-infra-style]
source = "https://github.com/qubit-ltd/rs-infra-style.git"
revision = "a8c684725727c8d05fdc41f05186da0063ce1bc6"
binary = "rs-infra-style"
package = "qubit-infra-style"

[rs-infra-verify]
source = "https://github.com/qubit-ltd/rs-infra-verify.git"
revision = "fbf307d951af502d718a1b2f575f92c44afe75f6"
binary = "rs-infra-verify"
package = "qubit-infra-verify"

[rs-infra-coverage]
source = "https://github.com/qubit-ltd/rs-infra-coverage.git"
revision = "672ac85f556e0de421fb5726c5048f1dd620b4dd"
binary = "rs-infra-coverage"
package = "qubit-infra-coverage"

[rs-infra-pages]
source = "https://github.com/qubit-ltd/rs-infra-pages.git"
revision = "93063e40697d2e3982f17e1c570ce3a3444829ea"
binary = "rs-infra-pages"
package = "qubit-infra-pages"

[rs-infra-ci]
source = "https://github.com/qubit-ltd/rs-infra-ci.git"
revision = "f796961216763dc1f5e0c98918ee815a1cc4b9dc"
binary = "rs-infra-ci"
package = "qubit-infra-ci"

[rs-infra-dependency]
source = "https://github.com/qubit-ltd/rs-infra-dependency.git"
revision = "7fd916875dd30b3788fc2a0adb35d3502749fcae"
binary = "rs-infra-dependency"
package = "qubit-infra-dependency"
